### ISSUE TITLE
[dataset] NEED4TWEET

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#159]
Please implement the following datasets:
https://github.com/badiehm/TwitterNEED

**Comment by renespeck** [comment]
Do 'you' will implement the annotator too? I the code available?

**Comment by MichaelRoeder** [comment]
@renespeck sry for the late response. If you know were the annotator is available (as open source or as web service) please create a new issue as this one is for the dataset :wink:

**Comment by MichaelRoeder** [comment]
Added by #251
