### ISSUE TITLE
Overview broken

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#162]
If I go to http://gerbil.aksw.org/gerbil/overview and click D2K > Show table 

Microposts 2013 and Derczynski look too low. Please look into it whether a good annotator like WAT works here or not. 

![image](https://cloud.githubusercontent.com/assets/4354740/19891020/6c144c26-a03e-11e6-929c-940bba9a12be.png)

**Comment by renespeck** [comment]
Derczynski dataset is/was broken, I tried to fix but did not tested yet. (00086383f275beb7ed9192a381f73028cfc85fa1)

**Comment by RicardoUsbeck** [comment]
@TortugaAttack can you please have a look?
