### ISSUE TITLE
Qanary intergation

### ISSUE THREAD

**Issue by D063520** [dice-group/gerbil#196]
The existing Qanary in the "System" option should be removed since the idea of Qanary is to compose a QA pipeline and to benchmark it after. Therefore we suggest instead of the option a link to:
https://wdaqua-qanary.univ-st-etienne.fr/gerbil
where a gerbil interface for a desired pipeline can be generated.
Salut
D063520

**Comment by RicardoUsbeck** [comment]
Hi, 

we will remove QANARY and add a CSS box below the "Add your own annotator" box saying: "Hint: you can also configure a QANARY pipeline and test it with GERBIL QA <URL>"

**Comment by D063520** [comment]
Yes, this is fine for us. Maybe when clicking you can redirect to: 

https://wdaqua-qanary.univ-st-etienne.fr/gerbil

Salut
Dennis

**Comment by MichaelRoeder** [comment]
## Task description

* QANARY should be removed by removing its definition from the https://github.com/dice-group/gerbil/blob/QuestionAnswering/src/main/properties/annotators.properties file.
* A small box below the "Add your own annotator" box saying: "Hint: you can also configure a QANARY pipeline and test it with GERBIL QA" with a link to https://wdaqua-qanary.univ-st-etienne.fr/gerbil should be added to the config page: https://github.com/dice-group/gerbil/blob/QuestionAnswering/src/main/webapp/WEB-INF/views/config.jsp

A volunteer should be able to handle HTML/CSS.

## Forking / Merging

The solution should be implemented in a branch, forked from the `QuestionAnswering` branch of the project. The pull request should merge the solution back into the `QuestionAnswering` branch.

## Responsible contact
[Ricardo Usbeck](http://cs.uni-paderborn.de/ds/team/team/)

**Comment by D063520** [comment]
You can put in the link instead of Qanary the QA system WDAqua-core0. The service is available under the following URI:

curl --data "query=Who is the wife of Barack Obama" https://wdaqua-qanary.univ-st-etienne.fr/gerbil-execute/wdaqua-core0,%20QueryExecuter/

**Comment by RicardoUsbeck** [comment]
Can this be closed?
