### ISSUE TITLE
Different visualisations for the overview page 

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#197]
Current drawbacks:
 * Hard to differentiate colours
 * the "shape" is not so important thus changing to bars or points and lines would be feasible
 *colors overlap, making the spider diagram hard to read

Suggestion by Ruben Verborgh: "The same information could be conveyed more clearly in a grouped bar chart."

**Comment by MichaelRoeder** [comment]
Should be combined with #188

**Comment by MichaelRoeder** [comment]
"Merged" this issue into #188 
Now, this is closed since it is a duplicate of #188
