### ISSUE TITLE
NER dataset on rare entities

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#201]
It would be good if this dataset is also available in GERBIL https://noisy-text.github.io/2017/emerging-rare-entities.html

**Comment by MichaelRoeder** [comment]
They are using the CoNLL format. We already implemented this for AIDA/CoNLL. However, it might have to be updated, since they seem to use some different types.

Overall, it looks like an easy task to add this as entity recognition and typing dataset.

**Comment by MichaelRoeder** [comment]
## Task description

Permanently adding a dataset to GERBIL is [described in the wiki](https://github.com/dice-group/gerbil/wiki/How-to-add-a-new-Dataset). There is already an adapter for the CoNLL format which should be reused.
* The code of the adapter can be found at https://github.com/dice-group/gerbil/blob/master/src/main/java/org/aksw/gerbil/dataset/impl/aida/AIDACoNLLDataset.java
* The definition of a dataset is explained on the wiki page linked above and an example for a CoNLL dataset can be found at https://github.com/dice-group/gerbil/blob/master/src/main/properties/datasets.properties#L15-L22

A volunteer should be able to program in Java to enhance the dataset adapter if necessary. Additionally, it would be good to briefly read through the [Semantic Web Journal paper](http://www.semantic-web-journal.net/content/gerbil-%E2%80%93-benchmarking-named-entityrecognition-and-linking-consistently).

Responsible contact: [Michael Röder](http://cs.uni-paderborn.de/ds/team/team/)
