### ISSUE TITLE
Illinois Wikifier and other missing annotators

### ISSUE THREAD

**Issue by sagnik** [dice-group/gerbil#204]
I am assuming the most complete discussion of the system is in [this paper](http://www.semantic-web-journal.net/system/files/swj1671.pdf) published in the Semantic Web Journal, 2016? Table 3 in that paper says that 20 annotators are available n the latest version of Gerbil, but I only see approximately 10-12, notably missing **Illinois Wikifier**. Here's a screen shot of my configuration. 

![sc](https://user-images.githubusercontent.com/4563472/28882291-d5dba156-7778-11e7-9dfb-afc92b981aab.png)

Is there something wrong with my config? Also, when I generate the table at [the experiment overview page](http://gerbil.aksw.org/gerbil/overview), For `Fred`, `KEA` and `TagMe` I see `error(-108)`. Is this expected?

**Comment by RicardoUsbeck** [comment]
Hi,

thanks for using GERBIL.

1) You selected the A2KB experiment type in your screenshot. Different experiment types have different annotators. Some annotators are used in more than one experiment type. So the total number stems from this configuration. 
2) Illinois Wikifier API had yielded some issues in the past. We are working on it. See also #172 
3) This table collect data from the latest runs for this particular type of experiment. That is, if someone run the last experiment with say KEA on a day where KEA was off or the server down, than the last database entry contains -108. So if you rerun a new experiment with KEA over all datasets in your chosen experiment type, the next time you click overview, the new stats will be present.
