### ISSUE TITLE
[NER] DoSeR: The annotator caused too many single errors

### ISSUE THREAD

**Issue by chelsea1992** [dice-group/gerbil#205]
Hi,

When I use DoSer Annotator, it says "The annotator caused too many single errors.". How can I fix it?

**Comment by TortugaAttack** [comment]
Hey,

i will have a look into it in the next days ;) 
I am currently testing if the DoSeR url is working. 

If you use it locally: could you provide the logs (a small representative view of the Errors should be enough)
If not which Dataset/Experiment Type did you use? (If you tried all, just write it, everything helps ;) )

**Comment by chelsea1992** [comment]
I use MSNBC and the website. http://gerbil.aksw.org/gerbil/config

BTW, how to run it locally? I can't find the how to use API documentation.

**Comment by TortugaAttack** [comment]
Thanks i wil look into the issue and try to fix it. 


To run it locally use this how to ;) 
https://github.com/dice-group/gerbil/wiki/How-to-setup-GERBIL

**Comment by TortugaAttack** [comment]
`ERROR [org.aksw.gerbil.http.AbstractHttpRequestEmitter] - <Response has the wrong status: HTTP/1.1 404 Not Found>` 

It seems that the DoSeR URL we use is not working anymore. 
@MichaelRoeder @RicardoUsbeck do you know something about it. Do you have a contact to the devs or an email?

**Comment by MichaelRoeder** [comment]
@quhfus does the URL of DoSeR has been changed?

**Comment by RicardoUsbeck** [comment]
what was the fix?

**Comment by TortugaAttack** [comment]
DoSeR seems to be offline for 3 years now (It hasn't been worked on since 2016)
@quhfus isn't responding. I got no mail which is working from him. Hence i would consider the online DoSeR demo dead (after talking with @MichaelRoeder)

**Comment by RicardoUsbeck** [comment]
Thanks for the answer

**Comment by TortugaAttack** [comment]
sorry should have wrote it down when i closed the issue.
