### ISSUE TITLE
[QA] Leaderboard

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#210]
Please reimplement the Leaderboard per dataset as done by @TortugaAttack for the SWChallenge branch.

**Comment by RicardoUsbeck** [comment]
What is the status?

**Comment by TortugaAttack** [comment]
Finished with commit [9c8736b](https://github.com/dice-group/gerbil/commit/9c8736bd5205f80aeab40e45b7d4c8e8e0f29050) 
Sorry thought i had it referenced and closed already

**Comment by TortugaAttack** [comment]
![screenshot_gerbilqa_leaderboard](https://user-images.githubusercontent.com/5443313/35231836-1cc6376c-ff9a-11e7-9d3c-057d0d9df5e7.png)
