### ISSUE TITLE
Codacy code quality

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#218]
Use https://www.codacy.com/ on GERBIL

**Comment by TortugaAttack** [comment]
hint: for autmatic review each commit and pull request check, dice-group needs to give codacy permission. ;)

**Comment by MichaelRoeder** [comment]
Feel free to configure it. @TortugaAttack could you take care of this?

**Comment by MichaelRoeder** [comment]
Status?

**Comment by TortugaAttack** [comment]
had auth problems
[![Codacy Badge](https://api.codacy.com/project/badge/Grade/962549badbc74930ad83bf2707c44762)](https://www.codacy.com/app/dice-group/gerbil?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=dice-group/gerbil&amp;utm_campaign=Badge_Grade)
