### ISSUE TITLE
[QA] Implement DBpedia-Entity v1 as dataset

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#220]
http://wiki.dbpedia.org/projects/dbpedia-entity

**Comment by MichaelRoeder** [comment]
QA?

**Comment by Suganya31** [comment]
@RicardoUsbeck 

Hi Ricardo, I am able to load the DBpedia-Entity v2  dataset but I have two queries. It would be helpful if you could clarify them.

1.  The following link says that the answers with 0 scale in [qrels-v2.txt](https://github.com/iai-group/DBpedia-Entity/blob/master/collection/v2/qrels-v2.txt) are irrelevant. Should I ignore those answers while adding it to the golden answers? 

https://github.com/iai-group/DBpedia-Entity#relevance-judgments

2. There are four types of queries in the dataset. Do I need to use this information somewhere?

https://github.com/iai-group/DBpedia-Entity#queries

Thanks,
Suganya

**Comment by RicardoUsbeck** [comment]
1.) please add them anyway 2) it make sense to make four dataset out of:

DBpedia-Entity_ SemSearch_ES
DBpedia-Entity_ QALD_2 and so on
