### ISSUE TITLE
[SWC] add delete token

### ISSUE THREAD

**Issue by TortugaAttack** [dice-group/gerbil#225]
As discussed at ISWC2017:
The whish was to delete a record, as some may not be statisfied by it. 

- Create unique delete token which will be shown after experiment started
- on Experiment Site: create delete button (X) which will show a popup where you can set the delete token
- which will then delete the record from the experiments. 

(maybe with a predefined time slot: token is only usable for 2 days, or something like that)

**Comment by MichaelRoeder** [comment]
Please add a configuration flag for enabling/disabling this feature. I can imagine cases in which you want to archiv records and thus nobody should be able to delete them.
