### ISSUE TITLE
[QA] Qanary wrong label

### ISSUE THREAD

**Issue by D063520** [dice-group/gerbil#241]
Hi, 

could you please move in gerbil for qa the name "qanary" to "wdaqua-core1". The first is only the architecture. And you are benchmarking the QA system, not the architecture. 

Thank you
Dennis

**Comment by D063520** [comment]
Hello,

the qanary endpoint is only partially working anymore and will probably not be maintained in future. Please switch, together with the name, also the endpoint. The new one is:

http://wdaqua-core1.univ-st-etienne.fr/gerbil

It has exactly the same API as the endpoint before (+/- bugs, hopefully none). The new endpoint is also more performant. This would be important also for the upcoming QALD challenge.

Thank you
D063520

**Comment by D063520** [comment]
Sorry I just wanted to comment not to close!

**Comment by nikit91** [comment]
Hello @D063520 , 
While resolving this issue I came across the previously provided URIs which look something like this:

**For Wikidata:**
https://wdaqua-qanary.univ-st-etienne.fr/gerbil-execute/wdaqua-core1\,%20QueryExecuter/ 
**For DBpedia:**
https://wdaqua-qanary.univ-st-etienne.fr/gerbil-execute/wdaqua-core1\,%20QueryExecuter/?kb=dbpedia

Could you please tell how should the new URL structure look like?

Regards,
Nikit

**Comment by D063520** [comment]
Mhmmm, you implemented differently then I expected. So the curl commands are:

curl --data "query=Who is the wife of Barack Obama" --data "kb=dbpedia"  http://wdaqua-core1.univ-st-etienne.fr/gerbil

curl --data "query=Who is the wife of Barack Obama" --data "kb=wikidata"  http://wdaqua-core1.univ-st-etienne.fr/gerbil


So in fact it is a post on  http://wdaqua-core1.univ-st-etienne.fr/gerbil with parameters:

query for the question
kb for the knowledgebase
lang for the language

**Comment by D063520** [comment]
Hi @nikit91, 

any news on this?

Salut
Dennis

**Comment by nikit91** [comment]
Hello @D063520 ,

I am working on a couple of QA issues. During that, this will be fixed as well. A pull request with my changes will be created soon.

Regards,
Nikit

**Comment by D063520** [comment]
In the current online version this seams not to be fixed.

**Comment by TortugaAttack** [comment]
theoretically yes, as it is fixed. 
But due to deployment we found other bugs and are currently fixing them before the deploy. 
Should be finished by today ;)
