### ISSUE TITLE
Differences in performance (DBpedia spotlight)

### ISSUE THREAD

**Issue by alexanderpanchenko** [dice-group/gerbil#244]
I am curious about difference in results between the DBpedia annotator and the NIF based web service (available in a GERBIL branch) based on the DBPedia annotator as presented below:

<img width="643" alt="screen shot 2018-02-25 at 8 34 11 pm" src="https://user-images.githubusercontent.com/1456830/36645574-479a117a-1a6b-11e8-8be2-e0fa92630a9f.png">

I registered a new NIF based web service, which is available in the branch as explained here: https://github.com/dice-group/gerbil/wiki/How-to-create-a-NIF-based-web-service. 

The difference is very big but I would expect the results to be the same (as this is a simple wrapper). Is there any issue with my setup or I misunderstand something?

**Comment by alexanderpanchenko** [comment]
When one selects A2KB experiment numbers are the same (so I will close this ticket), but still interesting to figure out why for D2KB they are not (I guess because NER annotation is ignored)P: 

<img width="509" alt="screen shot 2018-02-26 at 11 08 33 am" src="https://user-images.githubusercontent.com/1456830/36664600-73669c72-1ae5-11e8-8796-879db4009cf5.png">

**Comment by MichaelRoeder** [comment]
The two examples are not exactly the same. The NIF-based web service example (https://github.com/dice-group/gerbil/blob/SpotWrapNifWS4Test/src/main/java/org/aksw/gerbil/ws4test/SpotlightClient.java#L48) uses a different service than the service that we are using for DBpedia Spotlight (https://github.com/dice-group/gerbil/blob/master/src/main/properties/annotators.properties#L50).

**Comment by alexanderpanchenko** [comment]
ok, i see. thank you
