### ISSUE TITLE
[QA] New System: SQG

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#253]
Please run a dockered version on of our servers (since there is no public IP).

Source code: Query Generation for Question Answering over Knowledge Bases github.com/asknowqa/sqg

**Comment by hamidzafar** [comment]
FYI, SQG is not complete QA system. It requires the input question and the entities and relations linked as well.

**Comment by RicardoUsbeck** [comment]
I do see now...
