### ISSUE TITLE
Result table format broken if an error message is mixed with large results

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/gerbil#280]
## Description

It seems like the colspan feature of the error message is not adapting itself to the number of results. See for example http://gerbil.aksw.org/gerbil/experiment?id=201809130000

**Comment by nikit91** [comment]
@MichaelRoeder 
This issue was fixed as part of pull request https://github.com/dice-group/gerbil/pull/265
In the commit https://github.com/dice-group/gerbil/pull/265/commits/68ceafd1fe7b75afe20f01b5ad54a88c541d4dab

**Comment by MichaelRoeder** [comment]
Deployed the latest version.
