### ISSUE TITLE
[KBC] Links to experiment in leaderboard

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/gerbil#284]
## Description

In some situations, the users would like to see more details of the results which are visible in the leaderboard. In such a case it would be good if the result in the leaderboard would be linked to an experiment which contains the full details.

**Comment by TortugaAttack** [comment]
![screenshot_2018-09-19 overview](https://user-images.githubusercontent.com/5443313/45751009-4c937c00-bc11-11e8-9aa4-4a30ca8e2fbf.png)
Would this be fine?

**Comment by MichaelRoeder** [comment]
Yes :+1: 

Personally, I would prefer to have the annotator name as a link instead of an additional column. What do you think?

**Comment by TortugaAttack** [comment]
I thought this as well, but it maybe confused with all experiments of this annotator instead of the actual experiment

**Comment by TortugaAttack** [comment]
maybe at the annotator name something like:
AnnotatorName (view Experiment) ?

**Comment by MichaelRoeder** [comment]
That is possible as well :thinking: 

We can also think about using an icon instead of "view Experiment"? Maybe :mag: or :arrow_right:

**Comment by MichaelRoeder** [comment]
@TortugaAttack please close the issue if it is completed.
