### ISSUE TITLE
Request for systems' results

### ISSUE THREAD

**Issue by erik-m88** [dice-group/gerbil#287]
Hi,
I would like to check previous evaluated systems on the entity_match results but the website only shows F measure results and the tables are mis-formatted (attached a picture).
Please provide me with the previous C2KB results.

<img width="1247" alt="screen shot 2018-10-05 at 6 21 46 pm" src="https://user-images.githubusercontent.com/43697981/46544185-9b0c7000-c8cb-11e8-8e1f-eae67e03e2be.png">

Thanks,
Erik

**Comment by RicardoUsbeck** [comment]
The table contains a lot of n.a. values, which means this dataset vs. this system vs. C2KB never ran before. Thus, to obtain the numbers, the best thing would be to configure your own experiment via http://gerbil.aksw.org/gerbil/config and cite the resulting URI in your papers. Let us know if you need more help?

**Comment by erik-m88** [comment]
Nice thanks. However some didnt output all results (attached the error) should I try again? 
<img width="388" alt="screen shot 2018-10-09 at 4 48 54 pm" src="https://user-images.githubusercontent.com/43697981/46673902-8e498e00-cbe3-11e8-894a-2e0818999ab7.png">
