### ISSUE TITLE
Multiple errors running GERBIL

### ISSUE THREAD

**Issue by ERamaM** [dice-group/gerbil#288]
I am developing a semantic annotator which I intend to validate using GERBIL. I have some questions regarding the usage of this tool:

1. What version of DBpedia uses GERBIL exactly? I am using what i think is the lastest version available (2016 at the time of this writing) but i have been unable to find any evidence regarding the version that is using GERBIL (whether it uses DBpedia 2016 indexes or DBpedia 3.9 indexes).

2. I have tried multiple versions of GERBIL locally and i have been unable to use any version after 1.2.5.

  - Current version (downloaded directly from the repository) is unable to calculate properly scores for any combination of annotator/datasets giving either zeros or just failing ("the annotator caused too many single errors"). That doesn't happen on the public deployment of GERBIL (http://gerbil.aksw.org/gerbil). Furthermore, the measures on the public server and locally are not the same (public server gives more information):

![image](https://user-images.githubusercontent.com/12583530/46666818-0013de80-cbc8-11e8-880b-5b7443b51063.png)

  - Version 1.2.6 (in the releases tab) fails on watching an experiment results with the following error:

![image](https://user-images.githubusercontent.com/12583530/46664970-b70d5b80-cbc2-11e8-9529-633b06a3aa41.png)

  - Version 1.2.5 works fine.

3. My annotator focuses on solving C2KB and D2KB problems. For that, i developed a NIF WebService using Kotlin that interfaces my annotator with GERBIL . The implementation diverges a little from the wiki since i don't use NIF Transfer because i had problems with Apache Jena hanging on an infinite loop so i did it "manually". I don't have any problem with C2KB challenges but D2KB returns periodically nulls to my web service with the following error in GERBIL:

> 2018-10-09 10:22:48,967 [pool-1-thread-1] ERROR [org.aksw.gerbil.transfer.nif.AbstractNIFDocumentParser] - <Couldn't find any documents inside the given NIF model. Returning null.>

  Which causes my WebService returning a null and failing a test and, thus, failing completely the experiment when 15 errors accumulate (with DBpedia Spotlight dataset):

> 2018-10-09 10:22:48,968 [pool-1-thread-1] ERROR [org.aksw.gerbil.annotator.decorator.ErrorCountingAnnotatorDecorator] - <Got an Exception from the annotator (MyAnnotator (NIF WS)): null>

This issue also happens on the public server.

4. I have multiple errors like:

> java.io.FileNotFoundException: /home/user/Escritorio/prueba/gerbil/gerbil_data/cache/sameAs.cache_temp (No existe el archivo o el directorio)

- I suggest implementing a Dockerfile which deploys a local gerbil installation automatically. That avoids possible version conflicts of dependencies.

Thanks for your help and i apologize for any grammar mistake (i am not a native English speaker).

**Comment by MichaelRoeder** [comment]
Updated the issue by assigning numbers to the single points raised by the original author.

**Comment by MichaelRoeder** [comment]
Thanks for using GERBIL.

1. The question is not easy to answer.
    1. In general, GERBIL itself does not use any KB version. The gold standard defines the version.
    2. GERBIL can make use of a reference index / KB to make sure that entities mentioned in a dataset are still part of the latest version of the KB. The online instance of GERBIL uses an index based on DBpedia 2016-10.

2. The issue of v1.2.6 is known. We will check the problem of failing information (@TortugaAttack)

3. This is not possible to solve without getting the NIF files that your web service is sending. The error message seems to be clear: there is no RDF node for the document in your NIF file. Please provide us some examples of your systems output so that we can figure out the cause of this problem.

4. These errors are not influencing the quality of the results. As the error message describes, a directory is missing. So you can simply create the `/home/user/Escritorio/prueba/gerbil/gerbil_data/cache`.
Creating a docker image is one of our next goals. However, there are some preliminary steps that need to be carried out before doing that.

**Comment by ERamaM** [comment]
Thanks for your quick answer and for clearing my questions.

Attached there are 4 files that show the interaction of GERBIL ("request") with my web service ("response") with diferent datasets (i omited the lines containing the plain text to be analyzed). The lines "GOT AN EMPTY RESPONSE" refer to empty requests done to my web service (and, thus, answered with a null and failing). I hope this is the files you need.

Note that my web service autodetects when the challenge is D2KB (with detected terms supplied) or C2KB (only the text).

I don't clearly understand why datasets in D2KB mode like ace2004 seem to send only the text for evaluation (are the detected terms optional?).

[ace2004_purged.txt](https://github.com/dice-group/gerbil/files/2461463/ace2004_purged.txt)
[aquaint_purged.txt](https://github.com/dice-group/gerbil/files/2461464/aquaint_purged.txt)
[dbpediaspotlight_purged.txt](https://github.com/dice-group/gerbil/files/2461465/dbpediaspotlight_purged.txt)
[iitb_purged.txt](https://github.com/dice-group/gerbil/files/2461466/iitb_purged.txt)

**Comment by MichaelRoeder** [comment]
Thanks for the examples. Overall, they look fine but I am slightly confused whether you omitted the lines only in the files or whether your web service is not sending them as part of the response.

Could you please send a single example request/response pair to [me via mail](https://dice.cs.uni-paderborn.de/team/profiles/roeder/).

**Comment by TortugaAttack** [comment]
2) i checked the v1.2.5 - v1.2.6 diff and we changed the jena api from 2.x to 3.x which always causes these problems at some point due to the namespace change of jena if there is a hidden 2.X dependency. 
I will check and fix that asap

**Comment by MichaelRoeder** [comment]
You are right. I should have taken a closer look into the exception :open_mouth: 
It is a simple ClassNotFoundException which is classic for the version change as you pointed out. Good work :+1:

**Comment by TortugaAttack** [comment]
v1.2.6 should not have the depenceny error any more :)
