### ISSUE TITLE
The annotator caused too many single errors

### ISSUE THREAD

**Issue by erik-m88** [dice-group/gerbil#290]
Hi,

I tried running an experiment and most results were not reported due to ` The annotator caused too many single errors. ` How can I resolve this?

Thanks,

**Comment by MichaelRoeder** [comment]
Can you provide the ID of the experiment (or a link to the experiment)?

Typically, this error means that something is wrong with the annotation system and that was responding with errors instead of answers. If you are not the owner of the system, you can only point out the issue to the system owners and hope, that they can fix it.

**Comment by erik-m88** [comment]
@MichaelRoeder here is the link http://gerbil.aksw.org/gerbil/experiment?id=201810100000

**Comment by MichaelRoeder** [comment]
From the errors, it looks like there is not that much that you can do.

| Annotator | Issue | Solution |
|---|---|---|
| AIDA | Response has the wrong status: HTTP/1.1 500 Request failed. | Contact Developer |
| Dexter | Connect to dexterdemo.isti.cnr.it:8080 [dexterdemo.isti.cnr.it/146.48.82.49] failed: Connection timed out (Connection timed out) | Get new URL |
| Entityclassifier.eu NER | Response has the wrong status: HTTP/1.1 301 Moved Permanently | Get new URL |
| FRED | Response has the wrong status: HTTP/1.1 401 Unauthorized | Get credentials |
| TagMe 2 | Response has the wrong status: HTTP/1.1 500 Internal Server Error | Contact Developer |
| WAT | Connect to wikisense.mkapp.it:80 [wikisense.mkapp.it/131.114.137.211] failed: Connection timed out (Connection timed out) | Get new URL |
| xLisa-NER | unclear. See stack below. | Enhance error reporting of Adapter |
| xLisa-NGRAM | unclear. See stack below. | Enhance error reporting of Adapter |

@RicardoUsbeck  @TortugaAttack We should try to solve these issues. Maybe we even want to have regular checks for system availability :thinking: 

```
2018-10-12 13:38:40,502 [pool-26-thread-20] ERROR [org.aksw.gerbil.annotator.decorator.ErrorCountingAnnotatorDecorator] - <Got an Exception from the annotator (xLisa-NER)>
GerbilException: Couldn't send request to xLisa Annotator (error type -105: The annotator couldn't be loaded.)
        at org.aksw.gerbil.annotator.impl.xlisa.XLisaAnnotator.sendRequest(XLisaAnnotator.java:109)
        at org.aksw.gerbil.annotator.impl.xlisa.XLisaAnnotator.performC2KB(XLisaAnnotator.java:55)
```

**Comment by erik-m88** [comment]
alrighty, thanks!

**Comment by erik-m88** [comment]
also I noticed that the results of the experiments do not match the results shown in the experiment overview page (e.g., fox on AIDA/CONLL scores 45 while after running the experiment in the link it scores 57.91) I'm trying to understand why there is a huge difference. could provide any explanation? thanks

**Comment by MichaelRoeder** [comment]
I am slightly confused. AIDA/CoNLL is a dataset. Which annotator you are referring to?

**Comment by renespeck** [comment]
Hi, I checked the results of FOX from the link and the overview table and they are equal.

**Comment by erik-m88** [comment]
@renespeck Hi, could you refer me to the table you're talking about.

**Comment by erik-m88** [comment]
@renespeck attached is the results I'm comparing with, what table are your referring?
<img width="1140" alt="screen shot 2018-10-15 at 9 35 35 pm" src="https://user-images.githubusercontent.com/43697981/46970675-716cf900-d0c2-11e8-95f1-5e749e9f5911.png">

**Comment by renespeck** [comment]
The table is under the plot you posted. The 4th value is AIDA/CoNLL-Test B and 37th is MSNBC.
<br/>


 


<tr><td>FOX</td><td> 0.117</td><td> 0.562</td><td> 0.544</td><td> 0.579</td><td> 0.577</td><td> 0.350</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> 0.168</td><td> 0.202</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> 0.148</td><td> 0.290</td><td> 0.568</td><td> 0.207</td><td> 0.311</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> 0.472</td><td> 0.563</td><td> 0.576</td><td> 0.429</td><td> 0.517</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td><td> n.a.</td></tr>

**Comment by renespeck** [comment]
![screenshot_20181015_210926](https://user-images.githubusercontent.com/429427/46972440-ce66b000-d0be-11e8-93fa-9989f2472636.png)

**Comment by erik-m88** [comment]
@renespeck awesome! thank you so much

**Comment by erik-m88** [comment]
@renespeck how did you succeed to spread it out like that?

**Comment by renespeck** [comment]
I just zoomed out in my browser. ;)

**Comment by erik-m88** [comment]
@renespeck thanks a lot!
