### ISSUE TITLE
[D2KB] TagMe2 gives incorrect results. NERD-ML not showing on annotator list. 

### ISSUE THREAD

**Issue by ERamaM** [dice-group/gerbil#312]
Hello,

Multiple annotators available in D2KB experiment give incorrect results (WAT, XLisa, NERFGUN...). However, I'm specially concerned about three annotators: TagMe2, PBOH and NERD-ML. I tried them locally using gerbil-v1.2.5.

- I managed to get results from TagMe2 just by changing the API key to a new one i got from them (https://services.d4science.org/group/tagme/).

- NERD-ML doesn't appear on the annotators list. As far as i know, the API key should be put on a line such as "org.aksw.gerbil.annotators.NERD.key" but to check whether the annotator is available you are checking for the existence of a line such as "org.aksw.gerbil.annotators.nerd.Key". It could be quickly (and dirtly) fixed if in the configuration file the keys for NERD-ML are written as follows:

```
    org.aksw.gerbil.annotators.nerd.Key=
    org.aksw.gerbil.annotators.NERD.key=Your key HERE
```

Doing that trick i managed to get results from NERD-ML

~~- PBOH now gives zeros as a result. I got the same results from that annotator locally. An experiment showing that incidence is shown here: (http://gerbil.aksw.org/gerbil/experiment?id=201902280012)~~

UPDATE: seems that restarting the PBOH webservice fixed it.

Thank you.

**Comment by TortugaAttack** [comment]
- NERD-ML is fixed 
- TagMe Key is requested 

I will check the other Annotators today.

**Comment by ERamaM** [comment]
Thanks for your response.

I'm unable yet to see NERD-ML in the publicly deployed GERBIL version.

![imagen](https://user-images.githubusercontent.com/12583530/54268129-d433c500-457a-11e9-80b9-06eed52f737e.png)

TagMe2 is not working either (if i recall correctly, the key requesting of TagMe is almost instantaneous).

**Comment by TortugaAttack** [comment]
I did not update the online version yet. :)
Yes the user key is instantaneous, but we need an Application Key which has to be requested.

**Comment by TortugaAttack** [comment]
Done. 
new TagMe key added. 
will be working the next time gerbil is restarted (probably around next week)
