### ISSUE TITLE
How to calculate Macro F1 QALD Score

### ISSUE THREAD

**Issue by jannlemm0913** [dice-group/gerbil#320]
Hello, 

we (@silvanknecht and me) are trying to recreate some of the QALD-9 results and are now wondering, how the Macro F1 QALD Score is calculated. We know that the precision is 1 if the system gives no answer (instead of precision = 0), but that should not matter for the macro F1 (as it is calculated for every question). 

Is the F1 calculated from the global macro precision and recall? Or are we missing some cases where it matters that the precision is 1 even though the recall is 0 and therefore the F1 for that question is 0 aswell?

Thanks and kind regards

**Comment by RicardoUsbeck** [comment]
Hi, 
thanks for using GERBIL QA. In this paper, we describe it a bit more: http://www.semantic-web-journal.net/system/files/swj1838.pdf : 
![image](https://user-images.githubusercontent.com/4354740/58248883-a2e72a80-7d5d-11e9-9368-90cdd7f27dbb.png)

Maybe @TortugaAttack can point you to the code which implements that later.

**Comment by jannlemm0913** [comment]
A bit above the text you sent there is this: "For the macro metric, we calculate the precision, recall and F-measure per question and average these metrics individually at the end. " Is that for Macro F1 QALD different?

**Comment by TortugaAttack** [comment]
Hi 
Regarding the code:

QALD F1 Macro calculation 
https://github.com/dice-group/gerbil/blob/4d08ad0438688ef11b1bb68e515c344ba9e235d1/src/main/java/org/aksw/gerbil/evaluate/impl/FMeasureCalculator.java#L158

and the respective single precision,  recall and f1 measure calculations:
https://github.com/dice-group/gerbil/blob/4d08ad0438688ef11b1bb68e515c344ba9e235d1/src/main/java/org/aksw/gerbil/evaluate/impl/FMeasureCalculator.java#L174

**Comment by MichaelRoeder** [comment]
[Following the code](https://github.com/dice-group/gerbil/blob/QuestionAnswering/src/main/java/org/aksw/gerbil/evaluate/impl/FMeasureCalculator.java#L158), it is different, i.e., for the QALD macro F1, macro precision and macro recall are calculated and used to calculate the F1 measure. We implemented it only for backwards compatibility.

I would like to emphasize that this is not one of our ideas. It came from earlier QALD challenges where a script was used for the evaluation. (You can see the complete discussion from https://github.com/dice-group/gerbil/issues/211#issuecomment-334168618 on)

**Comment by jannlemm0913** [comment]
I see, thanks for the fast reply. We have read the issue but were unsure how the changes were implemented. Now we know and can refer to this issue in our work. Thank you.
