### ISSUE TITLE
Add FALCON as NER/NED tool

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#326]
https://labs.tib.eu/falcon/

**Comment by RicardoUsbeck** [comment]
Version 2.0 https://labs.tib.eu/falcon/falcon2/

**Comment by MichaelRoeder** [comment]
Seems to be only C2KB since the API does not seem to return the positions of the entities within the text :disappointed:

**Comment by RicardoUsbeck** [comment]
Unfortunately yes by now, maybe @AhmadSakor can add it in a new version?

**Comment by AhmadSakor** [comment]
I will add the new version soon. Also with the ability of returning the position of the extracted entities and relations
