### ISSUE TITLE
Add citation info

### ISSUE THREAD

**Issue by hamidzafar** [dice-group/gerbil#332]
Hey guys, 

Thanks for the good work. 

I couldn't find the citation information on the project's wiki. That would be nice to have the papers citation information somewhere on the first page or the wiki. 

Cheers,
Hamid

**Comment by MichaelRoeder** [comment]
That is a very good hint. Thanks :+1:

**Comment by MichaelRoeder** [comment]
For the Knowledge Extraction GERBIL, you can use the journal paper ["GERBIL–Benchmarking Named Entity Recognition and Linking Consistently"](https://dblp.uni-trier.de/rec/html/journals/semweb/RoderUN18)

For the Question Answering GERBIL, you can use the journal paper ["Benchmarking Question Answering Systems"](https://dblp.uni-trier.de/search?q=Benchmarking%20question%20answering%20systems)

Other (older) papers, like the WWW paper can be found at: http://aksw.org/Projects/GERBIL.html

**Comment by hamidzafar** [comment]
Thanks for your prompt answer.

**Comment by LukasBluebaum** [comment]
The citation information for the annotators and datasets can now be found on our website: https://dice-research.org/GERBIL
