### ISSUE TITLE
Non span entities

### ISSUE THREAD

**Issue by debayan** [dice-group/gerbil#336]
Hi

I am trying to convert lcquad 2.0 to nif format to upload to Gerbil. In this dataset the questions do not have entity spans mentioned. They only have entity URLs specified for the given question. So begin and end offsets, anchors etc do not make sense.
What would be the correct format for such NIF?  And what would be the right task (A2KB, C2KB etc) for this ?

**Comment by MichaelRoeder** [comment]
Your dataset would only fit to the `C2KB` experiment type. If you are using our classes, the [`Annotation`](https://github.com/dice-group/gerbil/wiki/Document-Markings-in-gerbil.nif.transfer#annotation) class is the solution you are looking for. If you are generating the NIF by yourself, you should use `nif:topic` for that.

**Comment by MichaelRoeder** [comment]
Let us know if you encounter problems with that.

If your question is answered, please close this issue :wink:

**Comment by debayan** [comment]
Yes, I have still not tried your solution, and will close the issue once your provided solution works out fine.

**Comment by RicardoUsbeck** [comment]
If you have the datasets (LCQuad V1 and V2) as NIF, could you please attach them here, so we can add them later?

**Comment by debayan** [comment]
Sure, when I do it I shall share. For now I am closing this issue. I have not been able to find the time to complete the nif conversion.
