### ISSUE TITLE
Issues with gerbil-qa local setup

### ISSUE THREAD

**Issue by lsiciliani** [dice-group/gerbil#338]
Hi everyone!
First of all, thank you for your work and support!

I am trying to configure the GERBIL local setup as explained [here](https://github.com/dice-group/gerbil/wiki/How-to-setup-GERBIL) but unsuccessfully.

The setup is done on an Ubuntu Server 18.06, with Apache Tomcat 7 and Java 8 and I'm testing GERBIL on the QALD 9 test set.
In attachment, you can find the complete log file, anyway, the main exceptions are:

- SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:*] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19

- Invalid cookie header: "Set-Cookie: WMF-Last-Access=04-Feb-2020;Path=/;HttpOnly;secure;Expires=Sat, 07 Mar 2020 00:00:00 GMT". Invalid 'expires' attribute: Sat, 07 Mar 2020 00:00:00 GMT
Invalid cookie header: "Set-Cookie: WMF-Last-Access-Global=04-Feb-2020;Path=/;Domain=.wikipedia.org;HttpOnly;secure;Expires=Sat, 07 Mar 2020 00:00:00 GMT". Invalid 'expires' attribute: Sat, 07 Mar 2020 00:00:00 GMT

- Couldn't parse the given SPARQL Query

[gerbil.log](https://github.com/dice-group/gerbil/files/4153129/gerbil.log)

Thank you in advance.

**Comment by TortugaAttack** [comment]
sorry for the late response.

All of the errors are not breaking and just bad logging. 
Now you can start gerbil-qa with `mvn clean package -Dmaven.test.skip=true cargo:run -Dcargo.servlet.port=5004` 

The parsing error is more of a warning, that the dataset has an invald SPARQL query thus the RE2KB experiment type will ignore the the sparql queries afaik.
