### ISSUE TITLE
Macro precision and recall are same?

### ISSUE THREAD

**Issue by debayan** [dice-group/gerbil#345]
Hi, For the following experiments I observe that macro precision, recall and F1 are all the same. I feel like there is some mistake somewhere. Can you help me figure it out?

Experiments:
http://gerbil.aksw.org/gerbil/experiment?id=202004010013
http://gerbil.aksw.org/gerbil/experiment?id=202004030001

Datasets:
nif files under https://github.com/debayan/wikidata-datasets

**Comment by RicardoUsbeck** [comment]
Could you please rerun it as A2KB and share the links with us? I suspect the C2KB experiment type has a not known bug since it is used rarely.

**Comment by MichaelRoeder** [comment]
Mhh... I do not really get why your dataset always uses to first character of a question to add the entities you would like to have (https://raw.githubusercontent.com/debayan/wikidata-datasets/master/webqsp/webqsp.test.nif) :thinking: 

However, A2KB and C2KB use the same classes in nearly all steps of the evaluation. I am not sure whether this is really a bug :thinking: 

| name | entitiesPerDoc | entitiesPerToken | avgDocumentLength | numberOfDocuments | numberOfEntities | numberOfEEs | numberOfRelations |
|---|---|---|---|---|---|---|---|
|webqsp.test.nif|0.9853569249542404|0.1479479662880176|6.660158633312996|1639|1615|0|0|

Not every document has an entity. I am not fully sure how our Macro Recall handles this case. :thinking:

**Comment by MichaelRoeder** [comment]
Regarding the dataset: if you want to add an entity to the question but it does not have a position within the text, you can use 
```
<http://sda.tech/webquestions/WebQTest-971> nif:topic <http://www.wikidata.org/entity/Q93349> .
```

**Comment by debayan** [comment]
Thanks for the quick response.

I am already re-running the experiment as A2KB, waiting for the results.

Regarding nif:topic, what if there are multiple entities in the question? Can I write it as:

<http://sda.tech/webquestions/WebQTest-971> nif:topic <http://www.wikidata.org/entity/Q93349>, <http://www.wikidata.org/entity/Q12345> .

**Comment by debayan** [comment]
http://gerbil.aksw.org/gerbil/experiment?id=202004060002 re-run on the same dataset but with a different backend (esel with a different reranking model). The macro p,r,f1 problem remains. I suppose the dataset is the issue. I will try with nif:topic now.

**Comment by MichaelRoeder** [comment]
> Regarding nif:topic, what if there are multiple entities in the question? Can I write it as:
```
http://sda.tech/webquestions/WebQTest-971 nif:topic http://www.wikidata.org/entity/Q93349, http://www.wikidata.org/entity/Q12345 .
```

Exactly :smile: 

The usage of `nif:topic` will not change the numbers. It was simply a hint from me that you may want to use an expression that fits much better :wink:

**Comment by MichaelRoeder** [comment]
Could you please upload the responses that you get for one of the datasets (maybe as nif file)? That would be much easier to help you dig into the problem.

**Comment by debayan** [comment]
I use the gerbil online demo, I do not run it locally. So I do not get any gerbil responses.

Also with this experiment http://gerbil.aksw.org/gerbil/experiment?id=202004060004 I think i figured it out. For multiple entities I have multiple blocks with different spans. The short sample dataset is at https://github.com/debayan/wikidata-datasets/blob/master/webqsp/webqsp.test.short20.nif

Regarding nif:topic the problem is I am using the pynif library and it does not seem to have nif:topic tag. I will find out a way to put it in myself.

**Comment by RicardoUsbeck** [comment]
Would be nice to see your final datasets online somewhere ;)

**Comment by debayan** [comment]
> Would be nice to see your final datasets online somewhere ;)

I am pretty close to that now.

**Comment by debayan** [comment]
So the A2KB output has 3 rows of numbers. What does the first row stand for? The 2nd row says "Entity Recognition". Is it the same as NER? My tool produces no NER related output, neither class names nor spans. So I wonder what the numbers in that row means. For example http://gerbil.aksw.org/gerbil/experiment?id=202004060004

**Comment by RicardoUsbeck** [comment]
Did you upload your final dataset to https://github.com/debayan/wikidata-datasets, @debayan ?

**Comment by debayan** [comment]
> Did you upload your final dataset to https://github.com/debayan/wikidata-datasets, @debayan ?

Yes, but I did not use nif:topic. And I am still running experiment on it. I am running Gerbil locally now.

Is there a way to kill gerbil tasks pre-maturely on the gerbil demo?

**Comment by MichaelRoeder** [comment]
Restart GERBIL. That is the safest and easiest way :thinking:
