### ISSUE TITLE
Adding ABACO to the list of default annotators

### ISSUE THREAD

**Issue by ERamaM** [dice-group/gerbil#357]
Hello,

First of all, thanks for maintaining GERBIL. It is a really useful tool.

I was wondering whether you could add ABACO to the list of default annotators. It exposes a NIF web service at http://tec.citius.usc.es/gerbilendpoint/

Currently, it only supports the D2KB experiment. Link to the paper: https://doi.org/10.1016/j.knosys.2020.105967

Thank you in advance.

**Comment by MichaelRoeder** [comment]
It seems like the endpoint of ABACO is not available, anymore.
@ERamaM do you know anything about that?

**Comment by ERamaM** [comment]
Thanks for noting me that. The machine that hosted the web service was down. It should be working now.

Cheers.
