### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jheinecke** [dice-group/gerbil#365]
Hi,
`mvn install` produces a compile error (`-DskipTests` does not help either)

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project gerbil: Compilation failure
[ERROR] /home/jeuh6401/GitHub/gerbil/src/test/java/org/aksw/gerbil/database/SimpleLoggingDAO4Debugging.java:[27,8] org.aksw.gerbil.database.SimpleLoggingDAO4Debugging is not abstract and does not override abstract method getResultNames() in org.aksw.gerbil.database.ExperimentDAO
```

**Comment by TortugaAttack** [comment]
There is def. something wrong with the `SimpleLoggingDAO4Debugging` class. It is just a debugging class. But I will check whats wrong with tomorrow morning.

**Comment by MichaelRoeder** [comment]
Sorry for the inconvenience. The problem should be solved now.

@TortugaAttack: I have been faster :stuck_out_tongue_winking_eye:
