### ISSUE TITLE
add new annotator in the select list

### ISSUE THREAD

**Issue by jheinecke** [dice-group/gerbil#367]
I'm suing Gerbil to test a new NE annotator (to be evluated on OKE 2005 task1). However, every time a run a test, I cannot go back to the "start" page and click "run experiment" a second time (I'm still working on the API of my anotator). So I have to reload the page `http://mymachine:1234/gerbil` and reconfigure from scratch. Could it be possible to have a "back" button somehow?
How could I add my annotator temporarily on the /gerbi page (on my local instance)?

**Comment by MichaelRoeder** [comment]
Do I get you right that you simply want to have your annotator in the drop down menu? 
You can do that as described here: https://github.com/dice-group/gerbil/wiki/How-to-add-a-new-Annotator#add-the-annotator-permanently

**Comment by jheinecke** [comment]
Yes and no, adding a new annotator was one thing (by the way I use `org.aksw.gerbil.annotators.definition.MOA.class=org.aksw.gerbil.annotator.impl.nif.NIFBasedAnnotatorWebservice` but since my GERBIL instance is running behind a firewall, it fails to check the returned dbpedia-instances of my annotator)
My question was, once I have started a test, I cannot restart it. I have to reload the page and reconfigure the experiment (task, data etc). It would be nice to get back to the initial page with all configuration still in place

**Comment by MichaelRoeder** [comment]
In that case, you can remove [these two lines](https://github.com/dice-group/gerbil/blob/master/src/main/webapp/WEB-INF/views/config.jsp#L559-L560) from the config.jsp file and restart GERBIL. This will keep the submit button in the form and you *should* be able to change the configuration and submit it again.

Please let me know if you encounter issues with this solution.

**Comment by jheinecke** [comment]
That is exactly what I was looking for. 
Thanks!
