### ISSUE TITLE
Structure of gerbil_keys.properties

### ISSUE THREAD

**Issue by redadmiral** [dice-group/gerbil#368]
Dear dice-group,
currently I'm trying to host gerbil on my own server to evaluate a EL system for German language texts. I start gerbil using the `docker_build.sh` and `run_gerbil.sh` script. Unfortunately the [system produces too many errors for every annotator except AIDA.](http://freieunibamberg.de:8080/gerbil/experiment?id=202011090002) 

Some of the errors like Babelfy's
```
java.lang.RuntimeException: Your key is not valid or the daily requests limit has been reached. Please visit http://babelfy.org.
```
or the one from xLisa
```
2020-11-10 01:40:51,196 [pool-1-thread-9] ERROR [org.aksw.gerbil.annotator.decorator.ErrorCountingAnnotatorDecorator] - <Got an Exception from the annotator (xLisa-NER): Couldn't send request to xLisa Annotator>
2020-11-10 01:40:51,220 [pool-1-thread-6] ERROR [org.aksw.gerbil.http.AbstractHttpRequestEmitter] - <Response has the wrong status: HTTP/1.1 401 Unauthorized>
```
let me assume that I need to provide credentials to the various annotators via `gerbil_keys.properties`. As you stated  [here](https://github.com/dice-group/gerbil/issues/16#issuecomment-61480110) this file shouldn't be shared. 

Is it possible for you to provide the structure of `gerbil_keys.properties` without sharing the actual keys? I'm not the best Java programmer and would like to avoid back-engineering this config file.

The full log (~19MB) of the experiment linked above can be found [here](
https://we.tl/t-uhYfb9yNgc). Link expires on the 17. November 2020.

Thanks for your work you've already invested in GERBIL – I really appreciate it and like the idea of having a general evaluation platform for increased reproducibility. 

Kind regards,
Marco

**Comment by MichaelRoeder** [comment]
Hi Marco,

thanks for using GERBIL :smiley: 

Most of the annotators don't need any authentication. I will have a look at your log to figure out what the problem is.

For annotators that need an authentication you should find a comment in the `annotators.properties` file, e.g., https://github.com/dice-group/gerbil/blob/master/src/main/properties/annotators.properties#L23-L24

@TortugaAttack It looks like it is not clearly documented where a user should look at. Can you please double check our wiki with respect to that?

**Comment by redadmiral** [comment]
Hi Michael,

thanks for answering this fast. I'll add the credentials to the `annotator.properties` and restart the experiment. The last one took my around 8h on my machine, so it'll take some time until I can tell you the results.

Thanks for having a look at my log file. For the experiment linked above I changed nothing but the timeout settings in `gerbil.properties`:

```
org.aksw.gerbil.annotator.http.HttpManagement.maxWaitingTime=60000
# Time interval at which a thread checks the current run times of HTTP requests (in ms)
org.aksw.gerbil.annotator.http.HttpManagement.checkInterval=5000
```

Setting up the system would have been easier for me if there were something like a first steps section on the wiki's main page. It was not clear to me which of the shell scripts I should execute in which order, or where to put the credentials for which annotator. I think those are problems many users new to GERBIL could face.

But thanks a lot for deploying it as a docker image :whale:! This makes it easier for me to deploy and run.

Best

**Comment by TortugaAttack** [comment]
Hey, 

The additional gerbil_keys are structured as follows:
```
org.aksw.gerbil.annotators.Babelfy.key=

org.aksw.gerbil.annotators.EntityclassifierEUConfig.apiKey=

org.aksw.gerbil.annotators.KeaAnnotatorConfig.user=
org.aksw.gerbil.annotators.KeaAnnotatorConfig.password=

```

I will add that to the wiki. 

xLisa does not need authentication, but the endpoint might just be moved. I will check on that.

**Comment by TortugaAttack** [comment]
regarding xLisa: https://github.com/dice-group/gerbil/issues/369

**Comment by TortugaAttack** [comment]
Added on how to set the keys for the annotators in https://github.com/dice-group/gerbil/wiki/How-to-get-API-keys

**Comment by redadmiral** [comment]
Thanks a lot for your help!

My main problem was that I ran the docker image which was not affected by any changes made to the property files. After starting GERBIL via the script (and trying it on different machines :roll_eyes: ) it now runs fine and every annotator working on the GERBIL instance hosted by you works on my machine too.

Please note that the [link to the TagMe help page in the wiki](https://github.com/dice-group/gerbil/wiki/How-to-get-API-keys) is dead. The link should point to [https://sobigdata.d4science.org/web/tagme/tagme-help](https://sobigdata.d4science.org/web/tagme/tagme-help).

**Comment by MichaelRoeder** [comment]
Sorry that you encountered these issues.

Thanks for the link. I updated it in our wiki accordingly :smiley:
