### ISSUE TITLE
DBPedia Spotlight moved

### ISSUE THREAD

**Issue by redadmiral** [dice-group/gerbil#372]
Hi everybody, 
DBPedia Spotlight moved it's endpoint. The current one is [https://api.dbpedia-spotlight.org/en/](https://api.dbpedia-spotlight.org/en/). 

Replacing the old one ([http://model.dbpedia-spotlight.org/en/](http://model.dbpedia-spotlight.org/en/))  in the `annotators.properties` makes it work again.

I'm glad at least this issue should be easy to fix :)

Thanks for your support and have a nice weekend!
Marco

**Comment by MichaelRoeder** [comment]
Thanks a lot of this information! :smiley:
