### ISSUE TITLE
What are the form of new data sets

### ISSUE THREAD

**Issue by xqx1568** [dice-group/gerbil#375]
I did experience in permanent uri：http://gerbil-qa.aksw.org/gerbil/config.But I meet a mistake:dataset can not be load.
What type of file show be upload? I think .json?
And what is the format of json file?
what details should I upload?
Include question or answer?

 And I want to know if I can get the details of F1 score and percision of each question.

**Comment by RicardoUsbeck** [comment]
Thank you for using GERBIL QA!

Please have a look here for the required format of the dataset https://github.com/dice-group/gerbil/wiki/Question-Answering

Currently, it is not possible to get the fine-grained results per question, but you can find out more about it in this issue https://github.com/dice-group/gerbil/issues/331

**Comment by xqx1568** [comment]
Thank you very much!
