### ISSUE TITLE
InKB, EE, GSInKB scores in D2KB

### ISSUE THREAD

**Issue by ozgesevgili** [dice-group/gerbil#379]
Hello,

I am currently using GERBIL v1.2.8 on a D2KB task. However, I couldn’t get InKB, EE, and GSInKB score results on the experiment page.

<img width="1156" alt="Screen Shot 2021-02-27 at 22 31 53" src="https://user-images.githubusercontent.com/6892804/109400941-e5369600-794b-11eb-9da0-457705d3bbfe.png">

Why could I not get InKB, EE, and GSInKB score results?

**Comment by MichaelRoeder** [comment]
Thanks for using GERBIL. I am sorry that you encountered this issue. We will look into it ASAP.

**Comment by MichaelRoeder** [comment]
The problem should be fixed. Please check out the latest version from the master branch and rebuild GERBIL (e.g., by running `start.sh`).

Please do not hesitate to reopen this issue if the problem is not fixed for you.

**Comment by ozgesevgili** [comment]
It works. Thanks for the quick fix.
