### ISSUE TITLE
Evaluate Custom Spotlight annotator with Wikidata dataset

### ISSUE THREAD

**Issue by jmdu99** [dice-group/gerbil#389]
Hi again!

My custom Spotlight annotator detects some Wikidata entities. So to test it, I have made a sample NIF dataset with 15 Wikidata entries.

Before using GERBIL, I have manually tested how well it detected these entities and, of the 15 entities that I have in the dataset, it correctly detects most of the annotations in each corresponding sentence **when the Confidence Score is 0.5 (or less)**.

The point is that when I do a GERBIL experiment with my service and my dataset, I get too low precision, it doesn't match the tests I did before manually:
![spotlight](https://user-images.githubusercontent.com/48102058/115444954-8851b080-a215-11eb-938c-7f9aff439473.jpg)

I wanted to ask how GERBIL does to determine if an annotation is correct or not in this case (with Wikidata entities) because I also made a dataset with entities from DBpedia in Spanish and in that case the results obtained seem to be correct.

My sample wikidata dataset is this one: [wikidata_es.zip](https://github.com/dice-group/gerbil/files/6345819/wikidata_es.zip)

Thanks in advance!

**Comment by MichaelRoeder** [comment]
Can you please share the result file of your local service with us?

If you don't have the results as single file, you can have a look at these lines in your `gerbil.properties` file: https://github.com/dice-group/gerbil/blob/master/src/main/properties/gerbil.properties#L75-L77
There, you can configure that GERBIL should store the annotator's answers for debugging. If you have a look into this directory, you should find a file for your annotator-dataset combination.

**Comment by jmdu99** [comment]
`output` folder is empty for some reason :( 

`gerbil.properties` and `annotators.properties` files seem to be okey

I run gerbil using `start.sh`

[properties.zip](https://github.com/dice-group/gerbil/files/6349945/properties.zip)

**Comment by MichaelRoeder** [comment]
Sorry, it does not work for uploaded datasets by default. I added a fix for that. Please pull my latest changes and add ` (store)` to the name of your dataset.

**Comment by jmdu99** [comment]
Ok, thank you! I think what the problem is, please confirm if I am right.

GERBIL detects all the entities in a sentence, so as in the dataset there are only entities from Wikidata, but the annotator also detects entities from DBpedia, that is why the precision is so low, because apart from the 15 from Wikidata it also detects the rest from DBpedia. 

Results: [DBpedia_Spotlight_Wikidata-WikidataSpotlight-w-A2KB.ttl.gz](https://github.com/dice-group/gerbil/files/6352603/DBpedia_Spotlight_Wikidata-WikidataSpotlight-w-A2KB.ttl.gz)

Am I correct or doesn't work like that? If I'm correct, I wanted to ask if you have any ideas on how to test the entity recognition of DBpedia and Wikidata separately (apart from in a joint dataset), since in the Wikidata dataset it detects entities of DBpedia, unless only the concrete surface form is put as text, and in the case of a dataset only for DBpedia, it may also be the case that Wikidata entities are detected (on my local annotator). 

I also wanted to ask if you know of the existence of any dataset in NIF format for Spanish DBpedia, like the one that is included in GERBIL for English (but in Spanish).


Thank you very much in advance.

**Comment by MichaelRoeder** [comment]
Yes, you are right. GERBIL will take into account all annotations your annotator returns as part of its result.

I think the easiest way is to adapt the Spotlight annotator to filter the annotations. You could do that by changing the [Spotlight annotator](https://github.com/dice-group/gerbil/blob/master/src/main/java/org/aksw/gerbil/annotator/impl/spotlight/SpotlightAnnotator.java) as follows:
```java
    private String allowedNamespace = null;

    public SpotlightAnnotator(String url, String allowedNamespace) {
        client = new SpotlightClient(url, this);
        this.allowedNamespace = allowedNamespace;
    }
```

Depending on the experiment type that you choose, you should implement a simple filtering for the results that you receive from the Spotlight client. The result above looks like an A2KB experiment. Hence, you could change the `performA2KBTask` method as follows:
```java
    @Override
    public List<MeaningSpan> performA2KBTask(Document document) throws GerbilException {
        List<MeaningSpan> result = new ArrayList<MeaningSpan>(client.annotate(document));
        if(allowedNamespace != null) {
            return result.stream().filter(m -> checkMeaning(m)).collect(Collectors.toList());
        } else {
            return result;
        }
    }
    
    private boolean checkMeaning(Meaning meaning) {
        for(String uri : meaning.getUris()) {
            if(uri.startsWith(allowedNamespace)) {
                return true;
            }
        }
        return false;
    }
```
After that, you should create two spotlight annotators in your annotators.properties:
```
### DBpedia Spotlight ES (Wikidata)
org.aksw.gerbil.annotators.definition.spotlightESWiki.name=DBpedia Spotlight ES (Wikidata)
org.aksw.gerbil.annotators.definition.spotlightESWiki.experimentType=OKE_Task1
org.aksw.gerbil.annotators.definition.spotlightESWiki.cacheable=true
org.aksw.gerbil.annotators.definition.spotlightESWiki.class=org.aksw.gerbil.annotator.impl.spotlight.SpotlightAnnotator
org.aksw.gerbil.annotators.definition.spotlightESWiki.constructorArgs=https://api.dbpedia-spotlight.org/es/,https://www.wikidata.org/wiki
### DBpedia Spotlight ES (DBpedia)
org.aksw.gerbil.annotators.definition.spotlightESDBp.name=DBpedia Spotlight ES (DBpedia)
org.aksw.gerbil.annotators.definition.spotlightESDBp.experimentType=OKE_Task1
org.aksw.gerbil.annotators.definition.spotlightESDBp.cacheable=true
org.aksw.gerbil.annotators.definition.spotlightESDBp.class=org.aksw.gerbil.annotator.impl.spotlight.SpotlightAnnotator
org.aksw.gerbil.annotators.definition.spotlightESDBp.constructorArgs=https://api.dbpedia-spotlight.org/es/,http://dbpedia.org/resource
```

*I didn't had the time to test it properly. Please double check it whether it make sense for you and watch out for these guys:* :bug:

**Comment by jmdu99** [comment]
It works perfect, thank you very much!

I only have 2 questions left:

1. How can I change the listening address of GERBIL service? Instead of `localhost:1234/gerbil/`, something like `https://jdiaz.dbpedia.linkeddata.es/gerbil/`
2.  Do you know of the existence of any dataset in NIF format for Spanish DBpedia? Like the one that is included in GERBIL for English (but in Spanish). I mention it since I have made one dataset with 100 entities, but maybe it is more convenient to use one that already exists (which may try more entities with more variety of documents).

Thank you very much in advance.

**Comment by MichaelRoeder** [comment]
1. When you want to have an address like `https://jdiaz.dbpedia.linkeddata.es/gerbil/`, there are 4 different parts of the address which have to be defined at 4 different places and only 2 of them are related to GERBIL :wink: 

* `https`: you will need a certificate for the SSL/TLS connection that is part of HTTPS. This is independent of GERBIL
* `jdiaz.dbpedia.linkeddata.es`: you will have to talk to the people maintaining the DNS server of `linkeddata.es` to have a rule to forward the traffic to the server that hosts your GERBIL. This is also independent of GERBIL
* Port: the port can be defined in the [`start.sh`](https://github.com/dice-group/gerbil/blob/master/start.sh#L192) file by changing `1234` to the port you need.
* `/gerbil/`: the path is already the path that GERBIL uses. So there is no need to change something :+1: 

2. @renespeck suggested the automatically created WikiNER dataset. https://github.com/dice-group/FOX/tree/master/input/Wikiner  However, it is not a NIF dataset :thinking:

**Comment by MichaelRoeder** [comment]
@DiegoMoussallem suggested to have a look at https://github.com/juand-r/entity-recognition-datasets#spanish
