### ISSUE TITLE
AIDA annotation URL is not available

### ISSUE THREAD

**Issue by jangso417** [dice-group/gerbil#395]
Hello, 

When I set the experiment with AIDA_CONLL dataset at the local gerbil framework, 
the URL(https://gate.d5.mpi-inf.mpg.de/aida/service/disambiguate) is not available now.

It is configured in the annotators.properties file.
### AIDA
org.aksw.gerbil.annotator.Aida.ServieURL=https://gate.d5.mpi-inf.mpg.de/aida/service/disambiguate

Would you let me know how to solve this problem?

**Comment by MichaelRoeder** [comment]
Sorry for the very late answer :disappointed: 

We do not have any influence on the state of the annotation services and we are not aware of any other URL for this service.

I hope this answers your question.
