### ISSUE TITLE
Missing files: mapping_url and index_url

### ISSUE THREAD

**Issue by LeonardoEmili** [dice-group/gerbil#398]
Coming here from #366.

I have used this program some time ago and I noticed that the start script used invalid URLs to fetch the mapping and index files used by Gerbil.  As a temporary fix, I suggest updating the script with Leipzig University links that work fine.
I haven't opened any PR that includes the updated links since I don't know if there is any copyright on it, but I can do it if that's okay with you.

Regards,
Leonardo Emili

**Comment by MichaelRoeder** [comment]
The [`start.sh`](https://github.com/dice-group/gerbil/blob/master/start.sh) script uses the new URLs and should work without issues.

Do you refer to the [`run-gerbil.sh`](https://github.com/dice-group/gerbil/blob/cbd91b74b4b229e284f5604f0e35d3d50cadc2f7/run-gerbil.sh) script? Or did you encounter old URLs somewhere else?

**Comment by LeonardoEmili** [comment]
Yes, the only broken links that I found are in the script `run-gerbil.sh`.

**Comment by MichaelRoeder** [comment]
The `run-gerbil.sh` will become obsolete with PR #396

**Comment by LeonardoEmili** [comment]
Okay, I will close the issue since the problem is solved.
