### ISSUE TITLE
[QA] Port change issue

### ISSUE THREAD

**Issue by nikit91** [dice-group/gerbil#419]
Hello,

In the Gerbil's QuestionAnswering branch, `start.sh` has the following argument passed to maven command:
`-Dcargo.servlet.port=5004`

However, I still get the error regarding port 8080 being unavailable:

```
[INFO] [en3.ContainerRunMojo] Resolved container artifact org.codehaus.cargo:cargo-core-container-tomcat:jar:1.9.11 for container tomcat9x
[INFO] [beddedLocalContainer] Tomcat 9.x Embedded starting...
[WARNING] [beddedLocalContainer] org.codehaus.cargo.container.ContainerException: Port number 8080 (defined with the property cargo.servlet.port) is in use. Please free it on the system or set it to a different port in the container configuration.
[ERROR] Starting container [org.codehaus.cargo.container.tomcat.Tomcat9xEmbeddedLocalContainer@7a5c6d8] failed
org.codehaus.cargo.container.ContainerException: Port number 8080 (defined with the property cargo.servlet.port) is in use. Please free it on the system or set it to a different port in the container configuration.
```

For now, I am using a work-around that involves providing the port directly in the `pom.xml` instead ( Ref: https://codehaus-cargo.github.io/cargo/Configuration+properties.html#Configurationproperties-MavenPlugin)

It seems that even after providing a port through the commandline the codehaus cargo plugin goes and checks availability of the default port first (8080).

**Comment by arjanoop** [comment]
This issue appears to be non-replicable at the moment. It is possible that the third-party Codehaus Cargo library has resolved this problem in a recent update, thereby preventing the issue from occurring. If you continue to experience the issue, please reopen the bug.

Findings: 
By launching the application using start.sh
![image](https://github.com/dice-group/gerbil/assets/41595802/a851559e-d661-4867-b897-e88b2b942cb3)
![image](https://github.com/dice-group/gerbil/assets/41595802/be10ade2-0bc1-4650-a0da-058a6928b37a)
