### ISSUE TITLE
Error running experiment with DBPedia Spotlight on N3-Reuters-128

### ISSUE THREAD

**Issue by dukesun99** [dice-group/gerbil#425]
Experiment ID: http://gerbil.aksw.org/gerbil/experiment?id=202303140000
Wanted to understand how this library works. May I check if it is expected or not?

**Comment by MichaelRoeder** [comment]
I am travelling at the moment. I will have a look at your issue as soon as I am back.
I apologize for the inconveniences this may cause.

**Comment by MichaelRoeder** [comment]
It worked for me: http://gerbil.aksw.org/gerbil/experiment?id=202303210000
I assume that there was some communication error between GERBIL and DBpedia Spotlight (e.g., maybe the Spotlight service was down for maintenance) or something similar.
