### ISSUE TITLE
sorry,i donot know whether this can run on my linux and just put the url in edge/chrome , or i should use the api? or the

### ISSUE THREAD

**Issue by eatinghungry** [dice-group/gerbil#426]

**Comment by eatinghungry** [comment]
<img width="1107" alt="678e9201d357a2574b8f468cdda6977" src="https://user-images.githubusercontent.com/50476089/225545842-aedd2675-ac57-40f1-8b77-ba0ff69d9f0e.png">

Do this mean that the program ran successfully？？

**Comment by MichaelRoeder** [comment]
Hello and thank you for your interest in our project :slightly_smiling_face: 

If you tried to start GERBIL locally on your machine, it didn't work. Could you please give a little bit more details about what you would like to achieve and what exactly your tried to do?

**Comment by eatinghungry** [comment]
i want  to follow the ENTQA and use  it in EL(entity link) tasks, and when i use  wget  http://localhost:1234/gerbil it return 404, when i use  wget  http://localhost:1234, it can return a html. but i can't find the place to enter http://localhost:1235/gerbil-spotWrapNifWS4Test/myalgorithm, and if i curl this url ,it would return error.

![image](https://user-images.githubusercontent.com/50476089/226265674-cd24bf41-4bfd-4dcc-87cd-b2819f521e84.png)
![image](https://user-images.githubusercontent.com/50476089/226266026-eed87445-6a8e-4292-8ef2-5288c42cf1dd.png)

**Comment by MichaelRoeder** [comment]
1. Is there a reason why you want to start an experiment with `curl`? Using a "normal" browser might be easier. However, `curl` is possible as well but needs some more explanation.
2. Did you follow the steps to setup GERBIL explained in [the wiki](https://github.com/dice-group/gerbil/wiki/How-to-setup-GERBIL)?

**Comment by MichaelRoeder** [comment]
Closed because of inactivity.
