### ISSUE TITLE
[QA] The about page does not work

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/gerbil#428]
https://gerbil-qa.aksw.org/gerbil/about does not work. Hence, the page is missing an "impressum".

**Comment by RicardoUsbeck** [comment]
Ups, can you copy https://gerbil.aksw.org/gerbil/about here?

**Comment by RicardoUsbeck** [comment]
That is a good point. However, isn't the contributors list transitive ;) ? But well https://semantic-web-journal.net/system/files/swj1578.pdf as a citation and deletion of contributors would be fine. If you could do that I would a) highly appreciate it and b) add a drink to the list of things I owe you!

**Comment by RicardoUsbeck** [comment]
Thanks a ton 🍻
