### ISSUE TITLE
[dataset] Ritter dataset wrapper

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#43]
Write a wrapper for the Ritter dataset dataset. 
Annotate the license, experiment type and language. 
Give provenance.
Update https://github.com/AKSW/gerbil/wiki/Licences-for-datasets

**Comment by RicardoUsbeck** [comment]
https://github.com/aritter/twitter_nlp/blob/master/data/annotated/ner.txt

**Comment by TortugaAttack** [comment]
This is nearly the same as UMBC (except with a little bit more specific Types) 
Should be easy to implemet.

**Comment by TortugaAttack** [comment]
Assuming: 
Facitlity   -> dbo:Place
Other      -> dbo:Unknown
Geo-Loc -> dbo:Place 

(Could not find a better mapping for those 3) 

It is finished and commited and Licence Site is updated.
